### ISSUE TITLE
error importing calinski_harabasz_score

### ISSUE THREAD

**Issue by AnnikaNoren** [learn-co-curriculum/dsc-market-segmentation-clustering-lab#1]
When I tried to import calinski_harabasz_score from  sklearn.metrics.cluster there is an error: 

ImportError: cannot import name 'calinski_harabasz_score'

I tried several variations and checked the sklearn documentation and the spelling with no success.

**Comment by lindseyberlin** [comment]
Should have been `from sklearn.metrics import ...` instead of `from sklearn.metrics.cluster` - now fixed
